# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks

# Global properties
separator=true
separator_block_width=15


[cpu]
label=cpu:
color=#afff75
command=sensors | grep CPU | awk '{print $2}'
interval=5

[mem]
label=mem:
color=#78bbff
command=mem.sh
interval=5

[bat]
label=bat:
color=#afff75
command=bat.sh
interval=50


[vol]
label=vol:
color=#78bbff
command=vol.sh
interval=once
signal=1


[time]
color=#afff75
command=date '+%a %d-%m-%Y|%H:%M:%S'
interval=5
