#!/bin/bash
CL=$(setxkbmap -query | awk '/layout/ {print $2}')

if [[ "$CL" == 'br' ]]; then
    setxkbmap -layout us -variant intl
else
    setxkbmap -model abnt2 -layout br -variant abnt2
fi

xmodmap -e "keycode 105 = slash question"
